In [104]:
from modulos.data_load import load
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [105]:
df = load('AAVEBTC')
df

,unix,date,symbol,open,high,low,close,Volume AAVE,Volume BTC,buyTakerAmount,buyTakerQuantity,tradeCount,weightedAverage
41405,1602288000000,2020-10-10 00:00:00,AAVE/BTC,0.003800,0.009801,0.003800,0.004801,0.001804,0.338493,0.0,0.0,0,0.005331
41404,1602352800000,2020-10-10 18:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000380,0.100026,0.0,0.0,0,0.000000
41403,1602356400000,2020-10-10 19:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000
41402,1602360000000,2020-10-10 20:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000
41401,1602363600000,2020-10-10 21:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,1751400000000,2025-07-01 20:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398
3,1751403600000,2025-07-01 21:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398
2,1751407200000,2025-07-01 22:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398
1,1751410800000,2025-07-01 23:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398
0,1751414400000,2025-07-02 00:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398

In [106]:
predictors = [ 'unix', 'high', 'low', 'open' ]
outcome = 'close'

X = df[predictors]
y = df[outcome]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-1.73337544,  2.81173427,  0.057891  ,  0.04552922],
       [-1.73186963,  0.03510084,  0.057891  ,  0.04552922],
       [-1.73178597,  0.03510084,  0.057891  ,  0.04552922],
       ...,
       [ 1.73183488, -0.61365809, -0.60681376, -0.61046133],
       [ 1.73191853, -0.61365809, -0.60681376, -0.61046133],
       [ 1.73200219, -0.61365809, -0.60681376, -0.61046133]],
      shape=(41406, 4))

In [107]:
y

41405    0.004801
41404    0.003800
41403    0.003800
41402    0.003800
41401    0.003800
           ...
4        0.002398
3        0.002398
2        0.002398
1        0.002398
0        0.002398
Name: close, Length: 41406, dtype: float64

In [110]:
regg = MLPRegressor(hidden_layer_sizes=(100,50), activation='relu', max_iter=500, random_state=1)
regg.fit(X_scaled, y)
regg.predict(X_scaled)

array([0.04444648, 0.00021526, 0.00021632, ..., 0.00323408, 0.00323501,
       0.00323594], shape=(41406,))

In [111]:
len(set(regg.predict(X_scaled)))

41406

In [113]:
dff = df
dff['PREDICTED'] = regg.predict(X_scaled)
dff

,unix,date,symbol,open,high,low,close,Volume AAVE,Volume BTC,buyTakerAmount,buyTakerQuantity,tradeCount,weightedAverage,PREDICTED
41405,1602288000000,2020-10-10 00:00:00,AAVE/BTC,0.003800,0.009801,0.003800,0.004801,0.001804,0.338493,0.0,0.0,0,0.005331,0.044446
41404,1602352800000,2020-10-10 18:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000380,0.100026,0.0,0.0,0,0.000000,0.000215
41403,1602356400000,2020-10-10 19:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000,0.000216
41402,1602360000000,2020-10-10 20:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000,0.000217
41401,1602363600000,2020-10-10 21:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000,0.000218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,1751400000000,2025-07-01 20:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.003232
3,1751403600000,2025-07-01 21:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.003233
2,1751407200000,2025-07-01 22:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.003234
1,1751410800000,2025-07-01 23:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.003235
0,1751414400000,2025-07-02 00:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.003236

In [114]:
dff = dff[[ 'symbol', 'date', 'close', 'PREDICTED' ]].rename(columns={ 'close': 'FECHAMENTO REAL' })
dff['ERRO'] = dff[['FECHAMENTO REAL', 'PREDICTED']].apply(lambda row: abs(row['FECHAMENTO REAL'] - row['PREDICTED']), axis=1)
dff

         symbol                date  FECHAMENTO REAL  PREDICTED      ERRO
41405  AAVE/BTC 2020-10-10 00:00:00         0.004801   0.044446  0.039646
41404  AAVE/BTC 2020-10-10 18:00:00         0.003800   0.000215  0.003585
41403  AAVE/BTC 2020-10-10 19:00:00         0.003800   0.000216  0.003584
41402  AAVE/BTC 2020-10-10 20:00:00         0.003800   0.000217  0.003583
41401  AAVE/BTC 2020-10-10 21:00:00         0.003800   0.000218  0.003582
...         ...                 ...              ...        ...       ...
4      AAVE/BTC 2025-07-01 20:00:00         0.002398   0.003232  0.000834
3      AAVE/BTC 2025-07-01 21:00:00         0.002398   0.003233  0.000835
2      AAVE/BTC 2025-07-01 22:00:00         0.002398   0.003234  0.000836
1      AAVE/BTC 2025-07-01 23:00:00         0.002398   0.003235  0.000837
0      AAVE/BTC 2025-07-02 00:00:00         0.002398   0.003236  0.000838

[41406 rows x 5 columns]

In [115]:
dff[dff['ERRO'] == dff['ERRO'].max()]

         symbol                date  FECHAMENTO REAL  PREDICTED      ERRO
41399  AAVE/BTC 2020-10-10 23:00:00         0.004801   0.044474  0.039674

In [116]:
dff[dff['ERRO'] == dff['ERRO'].min()]

         symbol                date  FECHAMENTO REAL  PREDICTED          ERRO
12610  AAVE/BTC 2024-01-23 14:00:00         0.002217   0.002217  1.867859e-08